name: Lighthouse
on: push # For every push, this action will be triggered
jobs:
  lighthouse:
    runs-on: ubuntu-latest #OS
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install && npm install -g @lhci/cli@0.8.x
#       - run: npm run build
#       - run: lhci autorun
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          runs: 1
          urls:
            https://komalagarwal1.github.io/Bankist_LH/
#           uploadArtifacts: true
#           serverBaseUrl: http://localhost:9001/
#           serverToken: 00e6cc7e-ad1b-425e-8af9-255529edd961
#           temporaryPublicStorage: true
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lhr
          path: '.lighthouseci' # This will save the Lighthouse results as .json files
